app = 'tooljet-byrdson'
primary_region = 'sin'
kill_signal = 'SIGTERM'
kill_timeout = '2m0s'

[build]
  image = 'tooljet/tooljet-ce:v3.20.112-lts'

#[deploy]
#  release_command = 'npm run db:setup:prod'
#  wait_timeout = '30m'
#
#  [deploy.release_command_vm]
#    size = 'shared-cpu-2x'
#    memory = '4gb'

[env]
  TOOLJET_HOST = 'https://tooljet.byrdsonservices.com'
  PORT = '8080'
  PGRST_HOST = 'localhost:3002'
  PGRST_SERVER_PORT = '3002'
  PGRST_DB_PRE_CONFIG = 'postgrest.pre_config'
  WORKER = 'false'
  DISABLE_SIGNUPS = 'true'
  DEPLOYMENT_PLATFORM = 'docker'
  NODE_TLS_REJECT_UNAUTHORIZED = '0'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 100
    soft_limit = 50

[[vm]]
  size = 'shared-cpu-2x'
  memory = '2GB'

[experimental]
  cmd = ["npm", "run", "start:prod"]